curl 'http://localhost:5001/hybrid-day-checkin/europe-west1/handleSelfCheckin' \
  -H 'Accept: */*' \
  -H 'Accept-Language: en-GB,en-US;q=0.9,en;q=0.8' \
  -H 'Connection: keep-alive' \
  -H 'Content-Type: application/json' \
  -H 'Origin: http://localhost:5173' \
  -H 'Referer: http://localhost:5173/' \
  -H 'Sec-Fetch-Dest: empty' \
  -H 'Sec-Fetch-Mode: cors' \
  -H 'Sec-Fetch-Site: same-site' \
  -H 'User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Mobile Safari/537.36' \
  -H 'X-Firebase-AppCheck: eyJraWQiOiJqN09vemciLCJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJzdWIiOiIxOjc0NDIwMzc5NjAyOTp3ZWI6OTQ3MmEyNTQ2MzkzZDM5NGJkMzQ1NCIsImF1ZCI6WyJwcm9qZWN0c1wvNzQ0MjAzNzk2MDI5IiwicHJvamVjdHNcL2h5YnJpZC1kYXktY2hlY2tpbiJdLCJwcm92aWRlciI6ImRlYnVnIiwiaXNzIjoiaHR0cHM6XC9cL2ZpcmViYXNlYXBwY2hlY2suZ29vZ2xlYXBpcy5jb21cLzc0NDIwMzc5NjAyOSOiJOQzVFYXY0cjVzbW9aYXRQNE4xMHBSZjVtWXdmcjZFcXJoMnJOLWZvajBNIn0.Ft9Iya-wLOuJNCfTN7mGakZqygxkDCWM2GspTdck_fK7Pk9rHvEUSLXDbZGx9OlvRggCsJSUJO_LJG1tQ3t0A4TyWYThrOZmrxMKgwUuT4eoGujvda3WjtUYWS_-F4dMx8S7uBsjs1o4QnM7uL50Uy4iNMDNx_CjHICM5jIQQcTLUn' \
  -H 'sec-ch-ua: "Chromium";v="134", "Not:A-Brand";v="24", "Google Chrome";v="134"' \
  -H 'sec-ch-ua-mobile: ?1' \
  -H 'sec-ch-ua-platform: "Android"' \
  --data-raw '{"data":{"token":"21grPzPXPcJ4xQ3dCts748C9dtZe","email":"jose.filipe.chavarria@gmail.com"}}'