name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Vue.js App
        run: |
          npm install --prefix frontend
          npm run build --prefix frontend

      - name: Decode and Create Service Account Key File
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > serviceAccountKey.json

      - name: Run Firestore Initialization
        run: |
          npm install --prefix init
          npm run init:firestore --prefix init

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project hybrid-day-checkin


