name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build Vue.js App
        working-directory: frontend
        run: |
          npm install
          npm run build

      - name: Decode and Create Service Account Key File
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" | base64 -d > serviceAccountKey.json

      - name: Install Dependencies
        working-directory: functions
        run: |
          npm install
          npm run build

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project my-project-id

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project hybrid-day-checkin


