name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: npm run install

      - name: Build Project
        run: npm run build

      - name: Set Up Firebase Authentication
        run: |
            echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/serviceAccountKey.json
            echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/serviceAccountKey.json" >> $GITHUB_ENV


      - name: Deploy Firebase Functions
        run: firebase deploy --only functions --project hybrid-day-checkin

      - name: Deploy to Firebase
        run: firebase deploy --project hybrid-day-checkin


