name: Deploy to Firebase

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --prefix frontend

      - name: Build Vue.js App
        run: npm run build --prefix frontend

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project hybrid-day-checkin

      - name: Check & Ensure Firestore Collection Exists
        run: bash scripts/check-firestore.sh hybrid-day-checkin events
